using System;
using Rapadura.Gameplay.Items;

namespace Rapadura.Gameplay.Inventory
{
    /// <summary>
    /// A single inventory slot's runtime state. Stores only the item id (not a direct asset
    /// reference) plus quantity/durability, so this class serializes cleanly to JSON — the
    /// actual <see cref="ItemDefinition"/> is resolved through <see cref="ItemDatabase"/>.
    /// </summary>
    [Serializable]
    public class InventorySlotData
    {
        public string itemId;
        public int quantity;
        public float currentDurability;

        // Optional procedural-affix data (Fase 3 — "Sistema de geração procedural de itens").
        // Populated only for items generated via ProceduralItemGenerator (Rare/Epic/Legendary
        // rolls); left null/empty for plain (non-generated) items so existing saves and code
        // that only ever touched itemId/quantity/currentDurability are unaffected. Stored as
        // parallel primitive arrays (affix id + rolled value), not a direct reference to
        // Items.Procedural.GeneratedItemInstance, because this class must stay JSON-serializable
        // via JsonUtility for SaveManager and GeneratedItemInstance is a plain runtime object
        // that resolves its affixes through AffixDatabase — only the ids/values need to persist.
        public string[] generatedAffixIds;
        public float[] generatedAffixValues;
        public string generatedName;

        public bool IsEmpty => string.IsNullOrEmpty(itemId) || quantity <= 0;

        /// <summary>True if this slot holds an item generated by ProceduralItemGenerator (has rolled affixes).</summary>
        public bool HasGeneratedAffixes => generatedAffixIds != null && generatedAffixIds.Length > 0;

        public static InventorySlotData Empty()
        {
            return new InventorySlotData { itemId = null, quantity = 0, currentDurability = 0f };
        }

        public void Clear()
        {
            itemId = null;
            quantity = 0;
            currentDurability = 0f;
            generatedAffixIds = null;
            generatedAffixValues = null;
            generatedName = null;
        }
    }
}
